### PR TITLE
update README and default configuration file, bump Souin to latest

### PR DESCRIPTION
**Pull request by frederichoule**

### CODE REVIEW

**Comment by darkweak** [comment]
Thank you for the documentation update @frederichoule 🚀
Delayed to the next Souin release date, I cross my fingers to have time today. After that we have to use the latest release to have the working feature.

**Comment by darkweak** [comment]
@frederichoule can you bump to the latest Souin version please?

**Comment by frederichoule** [comment]
Sure, gimme a few minutes.

**Review by darkweak — CHANGES_REQUESTED** [review]

**Comment by darkweak** [comment]
Thank you very much @frederichoule ! 🚀

**Pull request merged**
